In [1]:
import numpy as np

In [2]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [3]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

In [4]:
 #Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34}

In [6]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 10000

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[2448, 6746,  141, 6282, 5795],
       [3934,  512, 2040, 2670, 1636]])

In [7]:
# Q3. Write a code to normalize arr2.
np.percentile(arr1,25)


9.75

In [8]:

# Q4. How would you check if your numpy array has some missing values?

In [9]:

# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [10]:
#FROM HERE THE ANSWER STARTS

In [12]:

#Q1. From arr1 you have to fetch out every alternate column starting from col1
#ans1: 
#Using slicing in index 
q1=arr1[:,0::2]

q1

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [13]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [14]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 
#ans2: 
# {0,2,4}-- 1st,3nd and 5th column, that is alternate column from 1st col.
# {0,15,30}-- 1st, 4th and 6th row, that is gap of 2 from 1st row
# combining both will give our result
q2=arr1[::3,::2]
q2

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [15]:

# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 10000

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[6000, 2530, 4409,  167, 3510],
       [4500, 8839, 1650, 4260, 4486]])

In [16]:
# Q3. Write a code to normalize arr2.
# There are many method of Normalising-- simple, min-max, z-score or standard score
# Here below i have done by method Simple Feature scaling that is-- Xnew=Xold/Xmax
max=arr2.max()
min=arr2.min()
narray=arr2/max
narray

array([[0.67880982, 0.28623147, 0.49881208, 0.01889354, 0.39710374],
       [0.50910737, 1.        , 0.1866727 , 0.48195497, 0.50752348]])

In [17]:
# method 2:- 
# Ans:- Excepted answer for 
# Formula as given in above example explanation that is-- Xnew=(Xold-Xmin)/(Xmax-Xmin)
# Min-Max method--
mmarray=(arr2-min)/(max-min)
mmarray

array([[0.67262454, 0.27248616, 0.48916052, 0.        , 0.38549354],
       [0.49965406, 1.        , 0.17101015, 0.47197878, 0.49803967]])

In [18]:

# method 3(For normalisation):- Formula as given in above example explanation that is-- Xnew=(Xold-Mean)/(standard deviation)
# Z - score Method or standard Method--
"""This method is not considered for the above problen as this method is not used for normalise data in [0,1]"""
mean=arr2.mean()
std=arr2.std()
zarray=(arr2-mean)/std
zarray

array([[ 0.87229812, -0.66817441,  0.16598924, -1.71720512, -0.233113  ],
       [ 0.2063878 ,  2.13264437, -1.05884179,  0.09984215,  0.20017264]])

In [19]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai
#Ans4 - Research kr rhe hain 
# There is a function "np.isnan()".. but having problenm in passing arguments here like below
# "TypeError: ufunc 'isnan' not supported for the input types, 
#           and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''"

In [20]:
# Not as like isnan() but it check wether any dataa is missing or not
def check(arr):
    if np.nan in arr:
        return print("missing values")
    else:
        return print("no values missing")
check(narray)

no values missing


In [21]:
ar8=[1,2,np.nan,np.nan,90,88.0,90.0,np.nan]
check(ar8)

missing values


In [22]:

# After research foud out this function return an boolean array, 'True' represents data is missing  

np.isnan(ar8) # here worked bingo..

array([False, False,  True,  True, False, False, False,  True])

In [23]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [24]:

#ans5:
#First sorted the array then return the last nth value of the array.
#
#
def nthmax(arr,n):
    if n<=len(arr):
        arr.sort()
        return arr[-n]
    else:
        raise IndexError('n should not exceed the length of the array {}, which is {}, \n The value of n was: {}'.format(arr,len(arr),n))
a1=np.array([10,18,11,45,78,32])
nthmax(a1,4)


18

In [25]:
#Test1:
a2=np.array([12,34,40,7,1,0])
nthmax(a2,3)

12

In [26]:

# Test2:
a3=np.array([12,34,40,7,1,0])
nthmax(a3,1)

40